name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: C/C++ CI
      run: |
         gcc -o myapp github.c
    - name: Run tests
      run: |
        ./myapp

